apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front
spec:
  # type: ExternalName
  # externalName: function-service.default.svc.cluster.local
  selector:
    app: front
  sessionAffinity: None
  ports:
    - port: 8080
      targetPort: 8080
  externalTrafficPolicy: Local
  type: LoadBalancer
